name: 'NPM custom Action'
description: 'Installing and caching NPM Packages'
inputs:
  path-of-folder:  # id of input
    description: 'the path to cache'
    required: true
    default: 'node_modules'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: npm install
      shell: bash
        
    - name: Get npm cache directory
      uses: actions/cache@v4
      # id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      with:
        path: ${{inputs.path-of-folder}}
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}