on:
  pull_request:
    types:
      - opened

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Post PR Comment
        uses: sureshgithubrit/Docker-Action-pr-gihy-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} #by default it is having read access
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}
