name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
        
        - name: Get npm cache directory
          uses: actions/cache@v4
          # id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          
        # - name: Unit Testing
        #   run: npm test
          
        # - name: Archive Test Result
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: Mocha-Test-Result
        #     path: test-results.xml

    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: install node version - 18
          uses: actions/setup-node@v4
          with:
            node-version: 18
            
        - name: install dependencies
          run: npm install --save-dev mongodb-memory-server
        
        - name: Get npm cache directory
          uses: actions/cache@v4
          # id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        
        # - name: unit testing
        #   run: npm run coverage

        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: CodeCoverage Result
            path: coverage-result.xml
            retention-days: 5
      
    docker-login:
      name: containerization
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }} 
